-- src/main/resources/data.sql
INSERT INTO primary_skills (name, description) VALUES 
('Programming', 'Software development and coding skills'),
('AWS', 'Amazon Web Services cloud platform'),
('Database', 'Database management and administration'),
('DevOps', 'Development and operations practices'),
('Networking', 'Network infrastructure and security'),
('Data Science', 'Data analysis and machine learning'),
('UI/UX Design', 'User interface and experience design'),
('Mobile Development', 'iOS and Android app development'),
('Web Development', 'Frontend and backend web development'),
('Cloud Computing', 'Cloud platforms and services'),
('Cybersecurity', 'Information security and protection'),
('AI/ML', 'Artificial Intelligence and Machine Learning'),
('Big Data', 'Large-scale data processing'),
('IoT', 'Internet of Things development'),
('Blockchain', 'Distributed ledger technology'),
('QA Testing', 'Quality assurance and testing'),
('Project Management', 'Agile and traditional project management'),
('Business Analysis', 'Requirements analysis and solution design'),
('Technical Writing', 'Documentation and technical content creation'),
('IT Support', 'Helpdesk and technical support');

INSERT INTO secondary_skills (name, primary_skill_id) VALUES
('Java', 1),
('Python', 1),
('JavaScript', 1),
('C++', 1),
('C#', 1),
('EC2', 2),
('S3', 2),
('Lambda', 2),
('RDS', 2),
('MySQL', 3),
('PostgreSQL', 3),
('MongoDB', 3),
('Oracle', 3),
('Docker', 4),
('Kubernetes', 4),
('Jenkins', 4),
('Git', 4);