// src/main/java/com/dnb/skillassessment/payload/response/JwtResponse.java
package com.dnb.skillassessment.payload.response;

import java.util.Collection;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.springframework.security.core.GrantedAuthority;

@Data
@Getter
@Setter
public class JwtResponse {
    private String token;
    private String type = "Bearer";
    private Long id;
    private String username;
    private String email;
    private Collection<? extends GrantedAuthority> authorities;

    public JwtResponse(String accessToken, Long id, String username, String email, Collection<? extends GrantedAuthority> authorities) {
        this.token = accessToken;
        this.id = id;
        this.username = username;
        this.email = email;
        this.authorities = authorities;
    }
}
// Getters and setters are generated by Lombok annotations